const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {applyOperation,clients,createHandler}=require('../field-visits');
const seller={id:'seller-a',role:'seller'}, other={id:'seller-b',role:'seller'},admin={id:'admin',role:'admin'};
const now=()=>new Date().toISOString();
const op=(type,data)=>({id:randomUUID(),type,data});
function setup(){const db={users:[seller,other,admin],companies:[{id:'existing',name:'Cliente existente',address:'Av. Central'}]};const c={id:randomUUID(),name:'Tienda nueva',point:{latitude:-16.5,longitude:-68.1},createdAt:now()};applyOperation(db,seller,op('client',c));return {db,c};}
test('existing companies and new clients share directory; clients created offline replay only once',()=>{const {db}=setup();assert.equal(clients(db).length,2);const action=op('client',{id:randomUUID(),name:'Offline',point:{latitude:0,longitude:0},createdAt:now()});applyOperation(db,seller,action);applyOperation(db,seller,action);assert.equal(clients(db).length,3);assert.equal(clients(db)[2].createdBy,seller.id);});
test('arrival and finish preserve device time; replay after lost response is idempotent',()=>{const {db,c}=setup();const arrivedAt='2026-01-10T12:00:00.000Z',endedAt='2026-01-10T12:15:00.000Z';const start=op('arrival',{id:randomUUID(),clientId:c.id,arrivedAt,point:null,reason:'GPS no disponible'});applyOperation(db,seller,start);applyOperation(db,seller,start);const end=op('finish',{id:start.data.id,endedAt,result:'Pedido realizado',note:'Volver el lunes'});applyOperation(db,seller,end);applyOperation(db,seller,end);assert.equal(db.fieldVisits.length,1);assert.equal(db.fieldVisits[0].arrivedAt,arrivedAt);assert.equal(db.fieldVisits[0].endedAt,endedAt);});
test('a second active visit and another seller closing a visit are rejected',()=>{const {db,c}=setup();const start=op('arrival',{id:randomUUID(),clientId:c.id,arrivedAt:now()});applyOperation(db,seller,start);assert.throws(()=>applyOperation(db,seller,op('arrival',{...start.data,id:randomUUID()})),/anterior/);assert.throws(()=>applyOperation(db,other,op('finish',{id:start.data.id,endedAt:now(),result:'Sin pedido'})),/Solo el vendedor/);assert.equal(db.fieldVisits[0].endedAt,null);});
test('invalid coordinates and forged future dates are rejected; company location can be filled',()=>{const {db,c}=setup();assert.throws(()=>applyOperation(db,seller,op('location',{clientId:c.id,point:{latitude:95,longitude:0}})),/administrador/);assert.throws(()=>applyOperation(db,admin,op('location',{clientId:c.id,point:{latitude:95,longitude:0}})),/Coordenadas/);assert.throws(()=>applyOperation(db,seller,op('arrival',{id:randomUUID(),clientId:c.id,arrivedAt:'2999-01-01'})),/Fecha/);applyOperation(db,seller,op('location',{clientId:'existing',point:{latitude:-16,longitude:-68}}));assert.equal(clients(db)[0].point.latitude,-16);assert.throws(()=>applyOperation(db,other,op('location',{clientId:'existing',point:{latitude:0,longitude:0}})),/administrador/);});
test('API restricts access and seller histories while all sellers see all clients',async()=>{const {db,c}=setup();applyOperation(db,seller,op('arrival',{id:randomUUID(),clientId:c.id,arrivedAt:now()}));let response;const handler=createHandler({readDb:()=>db,mutateDb:async fn=>fn(db),body:async()=>({}),json:(res,status,data)=>{response={status,data};}});const get=async user=>{await handler({method:'GET'},{},new URL('http://localhost/api/field/data'),user);return response;};assert.equal((await get({id:'x',role:'client'})).status,403);assert.equal((await get({id:'x',role:'employee'})).status,403);assert.equal((await get(other)).data.clients.length,2);assert.equal(response.data.visits.length,0);assert.equal((await get(admin)).data.visits.length,1);assert.equal((await get(seller)).data.visits.length,1);});
test('finish rejects times before arrival and unsupported results',()=>{const {db,c}=setup(),id=randomUUID();applyOperation(db,seller,op('arrival',{id,clientId:c.id,arrivedAt:now()}));assert.throws(()=>applyOperation(db,seller,op('finish',{id,endedAt:'2020-01-01',result:'Sin pedido'})),/anterior/);assert.throws(()=>applyOperation(db,seller,op('finish',{id,endedAt:now(),result:'inventado'})),/resultado/);});
