const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),X=require('xlsx'),crypto=require('crypto');
const {importInventory}=require('../inventory-import');
const source=fs.readFileSync(require.resolve('../server'),'utf8'),context={crypto,clean:(value,max)=>String(value??'').trim().slice(0,max)};vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function inventoryNumber('),source.indexOf('function productPrice(')),context);
const run=(db,book)=>importInventory(db,book,{fileName:'test.xlsx',fileHash:'hash',importedBy:'Prueba'},context.validatedInventoryItem,context.inventoryRowHash);
const book=sheets=>{const w=X.utils.book_new();for(const [name,rows]of Object.entries(sheets))X.utils.book_append_sheet(w,X.utils.aoa_to_sheet(rows),name);return w;};
const db=()=>({inventoryItems:[],inventoryImports:[]});
test('all sheets validated before writing; reports every bad field and exact row',()=>{const data=db(),w=book({Correcta:[['Material','Calibre','Ancho'],['Bond',4,20]],Errores:[['Material','Calibre','Ancho'],[],['Bond',3.75,13.75]]});assert.throws(()=>run(data,w),e=>{assert.equal(e.status,422);assert.equal(e.errors.length,2);assert.ok(e.errors.every(x=>x.sheet==='Errores'&&x.row===3));assert.deepEqual(e.errors.map(x=>x.field),['calibre','ancho']);return true;});assert.equal(data.inventoryItems.length,0);assert.equal(data.inventoryImports.length,0);});
test('duplicates in file and inventory reject entire import',()=>{const data=db(),w=book({Uno:[['Material','ID'],['Bond','A1']],Dos:[['Material','ID'],['Bond','A1']]});assert.throws(()=>run(data,w),e=>e.errors.some(x=>x.cause.includes('Uno, fila 2')));assert.equal(data.inventoryItems.length,0);const valid=book({Uno:[['Material','ID'],['Bond','A1']]});assert.equal(run(data,valid).imported,1);assert.throws(()=>run(data,valid),e=>e.errors.some(x=>x.cause.includes('el inventario')));assert.equal(data.inventoryItems.length,1);assert.equal(data.inventoryImports.length,1);});
test('missing headers and Excel cell errors are reported; valid multiple sheets import together',()=>{const data=db();assert.throws(()=>run(data,book({Uno:[['Otro'],['Bond']]})),e=>e.errors.some(x=>x.cause.includes('encabezado')));const w=book({Uno:[['Material','Peso'],['Bond',1]]});w.Sheets.Uno.B2={t:'e',v:7,w:'#DIV/0!'};assert.throws(()=>run(data,w),e=>e.errors.some(x=>x.cause.includes('error de Excel')));assert.equal(data.inventoryItems.length,0);assert.equal(run(data,book({Uno:[['Material','ID'],['Bond','A1']],Dos:[['Material','ID'],['Bond','A2']]})).imported,2);assert.equal(data.inventoryImports.length,2);});
