const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(role='seller',storage=new Map()){
  let active=false,online=true,watchCount=0,clears=0;const calls=[];
  const window={dispatchEvent(){},addEventListener(){}};
  const context={window,me:{id:'seller-one',role},Event,AbortSignal,console,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},navigator:{geolocation:{getCurrentPosition:ok=>ok({coords:{}}),watchPosition:()=>++watchCount,clearWatch:()=>clears++}},fetch:async(url,options)=>{calls.push(url);if(!online)throw new TypeError('Offline');if(url.endsWith('/start'))active=true;if(url.endsWith('/stop'))active=false;return{ok:true,json:async()=>url.endsWith('/status')?{active}:url.endsWith('/team')?{people:[]}:{points:[]}};}};
  vm.runInNewContext(fs.readFileSync('public/journey-tracking.js','utf8'),context);
  return {controller:window.journeyTracking,storage,calls,setOnline:v=>online=v,stats:()=>({active,watchCount,clears})};
}
test('explicit start starts only one GPS watcher, stop ends it',async()=>{const h=harness();await h.controller.toggle();assert.equal(h.stats().active,true);assert.equal(h.stats().watchCount,1);await h.controller.load('seller-one');await h.controller.load('seller-one');assert.equal(h.stats().watchCount,1);await h.controller.toggle();assert.equal(h.stats().active,false);assert.ok(h.stats().clears>0);assert.equal(h.controller.state().pendingStop,false);});
test('offline stop persists intent, stops GPS locally and retries after reopening',async()=>{const h=harness();await h.controller.toggle();h.setOnline(false);await h.controller.toggle();assert.equal(h.controller.state().pendingStop,true);assert.equal(h.controller.state().active,false);assert.ok(h.stats().clears>0);const reopened=harness('seller',h.storage);await reopened.controller.load('seller-one');assert.ok(reopened.calls[0].endsWith('/stop'));assert.equal(reopened.controller.state().pendingStop,false);assert.equal(reopened.stats().watchCount,0);});
test('administrator reads monitoring without starting GPS or another seller shift',async()=>{const h=harness('admin');await h.controller.load('another-seller');await h.controller.toggle();assert.equal(h.stats().watchCount,0);assert.ok(h.calls.some(x=>x.endsWith('history?userId=another-seller')));assert.ok(!h.calls.some(x=>x.endsWith('/start')));});
